WEB_DRIVER_PATH = "C:\Program Files (x86)\chromedriver.exe"
CodeChefContest = "https://www.codechef.com/contests"
LeetCodeHeader = "https://leetcode.com"
LeetCodeGraphQL = "https://leetcode.com/graphql/"
LeetCodeContest = "https://leetcode.com/_next/data/Ldb_Fcc-UKa_pLAqMwyAp/problemset/all.json"